export const organization = "concat_ll";
export const locations = ["Artesa", "Girona", "Girona Interior", "La Tallada", "Lleida", "Solsona", "Tarragona", "Taradell", "Vic"];

// Factory functions for creating config objects
const createStatsConfig = (baseConfig, statsParams, attribute, stat, plotId, grouping = null) => ({
	...baseConfig,
	collection: baseConfig.wheatCollection,
	type: "stats",
	params: JSON.stringify({
		...statsParams,
		attribute: [attribute],
		stat,
		filters: [baseConfig.filter],
		group_by: grouping,
	}),
	plotId,
});

const concatConfigs = (site, startDate, endDate, year = null) => {
	// Base configuration
	const baseConfig = {
		project: "concat_ll",
		wheatCollection: "wheat__data",
		weatherCollection: "weather_data",
		filter: {
			property_name: "key",
			operator: "eq",
			property_value: site,
		},
	};

	const dateFilter = [
		{
			property_name: "timestamp",
			operator: "gte",
			property_value: startDate,
		},
		{
			property_name: "timestamp",
			operator: "lte",
			property_value: endDate,
		},
	];

	const statsBaseParams = {
		interval: "every_12_months",
		start_time: year ?? `${year}-01-01`,
		end_time: year ?? `${year}-12-31`,
	};

	return [
		// Metrics data config
		{
			...baseConfig,
			type: "data",
			collection: baseConfig.weatherCollection,
			params: JSON.stringify({
				attributes: ["timestamp", "key", "t_avg", "t_min", "t_max", "p", "sr"],
				filters: [baseConfig.filter, ...dateFilter],
				order_by: { field: "timestamp", order: "asc" },
			}),
			plotId: "metrics",
		},
		// Stats configs generated by factory function
		createStatsConfig(baseConfig, statsBaseParams.interval, "yield_value", "sum", "yield"),
		createStatsConfig(baseConfig, statsBaseParams.interval, "height", "avg", "height"),
		createStatsConfig(baseConfig, statsBaseParams.interval, "hlw", "sum", "hlw"),
		createStatsConfig(baseConfig, statsBaseParams.interval, "tkw", "avg", "tkw"),
		createStatsConfig(baseConfig, statsBaseParams.interval, "ng", "avg", "grain_number"),
		createStatsConfig(baseConfig, statsBaseParams, "yield_value", "sum", "yield_per_product", "var_code"),
		createStatsConfig(baseConfig, statsBaseParams, "height", "avg", "height_per_product", "var_code"),
		createStatsConfig(baseConfig, statsBaseParams, "hlw", "sum", "hlw_per_product", "var_code"),
		createStatsConfig(baseConfig, statsBaseParams, "tkw", "avg", "tkw_per_product", "var_code"),
		createStatsConfig(baseConfig, statsBaseParams, "ng", "avg", "grain_number_per_product", "var_code"),
	];
};

export default concatConfigs;
